export const ROUTES_UI = {
  DEFAULT: '',
  HOME: 'home',
  LOGIN: 'login',
  REGISTER: 'register',
  OTP_TEST: 'otpTest',
  FEED: 'feed',
  USER_POSTS_PAGE: 'user/:id',
  USER: 'user',
  SETTINGS: 'settings',
  FRIEND_REQUESTS: 'friendRequests',
  ADD_POST: 'addPosts',
  MESSENGER: 'messenger',
  UPDATE_POST: 'updatePost/:postId',
  UPDATE_POST_1: 'updatePost',
  WILDCARD_ROUTE: '**',
};

export const API_ROUTES = {
  BASE_URL: 'http://localhost:3400',
  LOGIN: '/user/login',
  REGISTER: '/user/register',
  ROOM_GET: '/prevChat',
  GET_CHAT: '/messages',
  SEARCH: '/user/search',
  SEND_OTP: '/otp',
  VERIFY_OTP: '/verifyOtp',
  FEED: '/feedForUser',
  CHECK_FRIENDS: '/friendsOrNot',
  PROFILE_DETAILS: '/user',
  USER_DETAILS: '/userDetails',
  LIKE_A_POST: '/likes',
  DISLIKE_A_POST: '/dislike',
  REMOVE_FRIEND: '/deleteFriend',
  SEARCH_USERS: '/searchUsers',
  FRIEND_REQUESTS: '/getFriendRequests',
  ACCEPT_FRIEND_REQUESTS: '/acceptRequest',
  SEND_REQUEST: '/sendRequest',
  GET_USER_FRIENDS: '/getUserFriends',
  ADD_POSTS: '/createPosts',
  PRIVACY: '/userPrivacy',
  UPDATE_PASSWORD: '/updatePassword',
  CHAT: '/chat',
  FRIENDS_LEN: '/friendsAll',
  ADD_COMMENT: '/addComment',
  GET_COMMENTS: '/getCommentsOfPost',
  SINGLE_POST: '/getUserSinglePost',
  CREATE_GROUP: '/createGroup',
  GET_GROUPS: '/getUserGroups',
  UPDATE_POST: '/updatePost',
  ADD_SOCKET: '/socket',
  REMOVE_SOCKET: '/removeSocket',
};

export const SOCKET_EVENTS = {
  CONNECTION: 'connect',
  DISCONNECT: 'disconnect',
  JOIN_ROOM: 'join-room',
  SEND_MESSAGE: 'send-message',
  RECEIVE_MESSAGE: 'receive-message',
  GROUP_JOIN: 'group-join',
  JOIN_BY_ROOM_NAME: 'join-by-room-name',
  JOIN_ROOMS_ALL: 'join-all-rooms',
  SEND_REQ_NOTIFICATION: 'send-req-notification',
  RECEIVE_FRIEND_REQ: 'request-notification',
  ACCEPT_REQ_NOTIFICATION: "accept-req-notification",
};
